class_name PixelArt
extends RefCounted
## Every sprite in the game, drawn as text: one character per pixel, each
## character a color from PALETTE ("." is transparent). Edit a row, rerun the
## game, and the sprite changes. Textures are built once and cached.
##
## "P" and "p" are recolored per player (their slot color and a darker shade),
## so every character works in every player color.
##
## Most sprites are left/right symmetric; keep them that way when editing.

const PALETTE: Dictionary[String, Color] = {
	".": Color(0, 0, 0, 0),
	"k": Color(0.09, 0.07, 0.11),
	"K": Color(0.27, 0.24, 0.31),
	"w": Color(0.95, 0.93, 0.88),
	"e": Color(1.0, 0.85, 0.35),
	"r": Color(0.8, 0.27, 0.27),
	"R": Color(0.5, 0.14, 0.18),
	"s": Color(0.56, 0.66, 0.48),
	"S": Color(0.37, 0.46, 0.32),
	"b": Color(0.84, 0.8, 0.68),
	"B": Color(0.56, 0.53, 0.45),
	"u": Color(0.52, 0.34, 0.66),
	"U": Color(0.31, 0.19, 0.42),
	"o": Color(0.92, 0.5, 0.17),
	"O": Color(0.6, 0.27, 0.1),
	"y": Color(1.0, 0.85, 0.4),
	"m": Color(0.68, 0.26, 0.45),
	"M": Color(0.42, 0.14, 0.29),
	"l": Color(0.56, 0.6, 0.7),
	"L": Color(0.33, 0.36, 0.45),
	"n": Color(0.33, 0.45, 0.25),
	"N": Color(0.21, 0.29, 0.16),
	"h": Color(0.48, 0.64, 0.42),
	"H": Color(0.3, 0.42, 0.27),
	"a": Color(0.74, 0.78, 0.32),
	"A": Color(0.48, 0.52, 0.18),
	"v": Color(0.5, 0.95, 0.55),
	"V": Color(0.24, 0.62, 0.34),
	"t": Color(0.4, 0.8, 1.0),
	"T": Color(0.18, 0.48, 0.7),
	"g": Color(0.85, 0.64, 0.25),
	"x": Color(0.13, 0.11, 0.16),
	"f": Color(0.93, 0.78, 0.63),
	"F": Color(0.72, 0.55, 0.42),
	"q": Color(0.5, 0.48, 0.55),
	"G": Color(0.34, 0.32, 0.38),
	"c": Color(0.42, 0.27, 0.16),
	"C": Color(0.27, 0.16, 0.09),
	"i": Color(0.78, 0.5, 1.0),
	"I": Color(0.46, 0.24, 0.72),
}

const SPRITES: Dictionary[String, Array] = {
	"wanderer": [
		"....kkkk....",
		"...kPPPPk...",
		"..kPPPPPPk..",
		"..kPkkkkPk..",
		".kPkekkekPk.",
		".kPkkkkkkPk.",
		".kPPkkkkPPk.",
		"kPPPPPPPPPPk",
		"kpPPPPPPPPpk",
		"kpPPPPPPPPpk",
		"kppPPPPPPppk",
		".kppPPPPppk.",
		".kkppppppkk.",
		"..kkk..kkk..",
	],
	"gravekeeper": [
		"...kkkkkkkk...",
		"...kxxxxxxk...",
		"...kxxxxxxk...",
		".kkkxxxxxxkkk.",
		"kxxxxxxxxxxxxk",
		".kkkkkkkkkkkk.",
		"..kffffffffk..",
		"..kfekffkefk..",
		"..kffffffffk..",
		".kPkBBBBBBkPk.",
		"kPPPkBBBBkPPPk",
		"kPPPPkkkkPPPPk",
		"kpPPPPPPPPPPpk",
		"kpPPPPPPPPPPpk",
		".kppppppppppk.",
		"..kkk....kkk..",
	],
	"hexblade_witch": [
		".....kk.....",
		"....kxxk....",
		"....kxxk....",
		"...kxxxxk...",
		"...kxxxxk...",
		"..kxxxxxxk..",
		"kkkxxxxxxkkk",
		".kkkkkkkkkk.",
		"..kffffffk..",
		"..kfeffefk..",
		"..kffffffk..",
		".kPkkkkkkPk.",
		"kPPPPPPPPPPk",
		"kpPPPPPPPPpk",
		".kpppPPpppk.",
		"..kkkkkkkk..",
	],
	"necromancer": [
		"....kkkk....",
		"...kxxxxk...",
		"..kxxxxxxk..",
		"..kxbbbbxk..",
		"..kxrbbrxk..",
		"..kxbbbbxk..",
		"..kxbkkbxk..",
		".kPkxbbxkPk.",
		"kPPPkkkkPPPk",
		"kpPPPPPPPPpk",
		"kpPPPuuPPPpk",
		"kpPPPPPPPPpk",
		".kpPPPPPPpk.",
		".kppPPPPppk.",
		"..kppppppk..",
		"..kkk..kkk..",
	],
	"bone_effigy": [
		"...kkkk...",
		"..kbbbbk..",
		".kbrbbrbk.",
		".kbbbbbbk.",
		"..kbkkbk..",
		"...kbbk...",
		".kkPbbPkk.",
		"kbbkbbkbbk",
		".kkkbbkkk.",
		"...kbbk...",
		"..kPbbPk..",
		"...kbbk...",
		"..kbbbbk..",
		".kkkkkkkk.",
	],
	"ghost": [
		"...kkkkkk...",
		"..kwwwwwwk..",
		".kwwwwwwwwk.",
		".kwkkwwkkwk.",
		".kwkkwwkkwk.",
		".kwwwwwwwwk.",
		".kwwwwwwwwk.",
		".kwwwwwwwwk.",
		".kwkwwwwkwk.",
		".kk.kwwk.kk.",
		".....kk.....",
	],
	"shambler": [
		"...kkkkkk...",
		"..kssssssk..",
		".kssssssssk.",
		".ksrssssrsk.",
		".kssssssssk.",
		".kSkkkkkkSk.",
		"..kSSSSSSk..",
		"ksOOOOOOOOsk",
		"kSkOOOOOOkSk",
		".k.OROORO.k.",
		"...kRkkRk...",
		"...kk..kk...",
	],
	"bat": [
		"k............k",
		"Uk..........kU",
		"uUk..kkkk..kUu",
		"uuUkkuuuukkUuu",
		".uuUuruuruUuu.",
		"..kUuuuuuuUk..",
		"....kUuuUk....",
		".....kkkk.....",
	],
	"bat_1": [
		".....kkkk.....",
		"....kuuuuk....",
		"...kuruuruk...",
		".kkUuuuuuuUkk.",
		"kuuUUuuuuUUuuk",
		"uuk.kUuuUk.kuu",
		"Uk...kkkk...kU",
		"k............k",
	],
	"ghoul": [
		"......kkkkkkkk......",
		"....kkRRRRRRRRkk....",
		"...kRRRRRRRRRRRRk...",
		"..kRRrrrrrrrrrrRRk..",
		"..kRrrrrrrrrrrrrRk..",
		".kRrrerrrrrrrrerrRk.",
		".kRrrrrrrrrrrrrrrRk.",
		".kRrkwkwkwwkwkwkrRk.",
		".kRrrkkkkkkkkkkrrRk.",
		"kRRrrrrrrrrrrrrrrRRk",
		"kRrrrrrrrrrrrrrrrrRk",
		"krRkrrrrrrrrrrrrkRrk",
		"krRkrrrrrrrrrrrrkRrk",
		"kwwkRrrrrrrrrrrRkwwk",
		".kk.kRrrrrrrrrRk.kk.",
		"....kRRrrrrrrRRk....",
		"....kRRRRRRRRRRk....",
		"....kRRkkkkkkRRk....",
		"....kRRk....kRRk....",
		"....kkkk....kkkk....",
	],
	"cultist": [
		"....kkkk....",
		"...kmmmmk...",
		"..kmmmmmmk..",
		"..kmkkkkmk..",
		".kmkekkekmk.",
		".kmkkkkkkmk.",
		".kmmkkkkmmk.",
		"kmmmmmmmmmmk",
		"kMmmgmmgmmMk",
		"kMmmmmmmmmMk",
		"kMMmmmmmmMMk",
		".kMMmmmmMMk.",
		".kMMMMMMMMk.",
		"..kkkkkkkk..",
	],
	"mire_crawler": [
		"..k.kk.k..",
		"...kkkk...",
		"..knnnnk..",
		".knennenk.",
		"knnnnnnnnk",
		"kNnNnnNnNk",
		"k.kNNNNk.k",
		".k.kkkk.k.",
	],
	"plague_spitter": [
		"...kkkkkk...",
		"..kaaaaaak..",
		".kaaaaaaaak.",
		".kaeaaaaeak.",
		"kaaaaaaaaaak",
		"kaAkkkkkkAak",
		"kaAkvvvvkAak",
		"kaAAkkkkAAak",
		"kAaaaaaaaaAk",
		".kAAaaaaAAk.",
		"..kAAAAAAk..",
		"...kkkkkk...",
	],
	"flame_imp": [
		"k........k",
		"ok..kk..ko",
		".kkooookk.",
		"kOkoyyokOk",
		"kOoeooeoOk",
		".kooooook.",
		"..kOooOk..",
		".kOkookOk.",
		".k.kOOk.k.",
		"....kk....",
	],
	"flame_imp_1": [
		"..........",
		"k...kk...k",
		"okkooookko",
		"kOkoyyokOk",
		"kOoeooeoOk",
		".kooooook.",
		"..kOooOk..",
		".kOkookOk.",
		"..kkOOkk..",
		"....kk....",
	],
	"fallen_paladin": [
		"......kkkkkk......",
		".....kLllllLk.....",
		"....kLllllllLk....",
		"....kLllllllLk....",
		"....kkooooookk....",
		"....kLllllllLk....",
		"...kkLLLLLLLLkk...",
		".kkllkLllllLkllkk.",
		"kllllkLlgglLkllllk",
		"kLLLLkLlgglLkLLLLk",
		"kLLkkLLlgglLLkkLLk",
		".kk.kLLllllLLk.kk.",
		"....kLLllllLLk....",
		"....kLLLLLLLLk....",
		"....kLLkkkkLLk....",
		"....kLLk..kLLk....",
		"....kLLk..kLLk....",
		"....kkkk..kkkk....",
	],
	"bone_warden": [
		"k......................k",
		"kk....................kk",
		".kBk................kBk.",
		".kBBk..............kBBk.",
		"..kBBk..kkkkkkkk..kBBk..",
		"...kBBkkbbbbbbbbkkBBk...",
		"....kkbbbbbbbbbbbbkk....",
		"....kbbbbbbbbbbbbbbk....",
		"...kbbbbbbbbbbbbbbbbk...",
		"...kbbkkkkbbbbkkkkbbk...",
		"...kbbkrrkbbbbkrrkbbk...",
		"...kbbkkkkbbbbkkkkbbk...",
		"...kbbbbbbbkkbbbbbbbk...",
		"...kBbbbbbbbbbbbbbbBk...",
		"....kBbbbbbbbbbbbbBk....",
		"....kBkwkwkwwkwkwkBk....",
		"....kBkkkkkkkkkkkkBk....",
		".....kBbbbbbbbbbbBk.....",
		"......kkBBBBBBBBkk......",
		"........kkkkkkkk........",
		"...kk.kKKKKKKKKKKk.kk...",
		"..kKKkKKKKKKKKKKKKkKKk..",
		".kKKKKKKKKKKKKKKKKKKKKk.",
		".kkkkkkkkkkkkkkkkkkkkkk.",
	],
	"mire_hag": [
		"...........kk...........",
		"..........kxxk..........",
		".........kxxxxk.........",
		".........kxxxxk.........",
		"........kxxxxxxk........",
		"........kxxxxxxk........",
		".......kxxxxxxxxk.......",
		"..kkkkkkxxxxxxxxkkkkkk..",
		".kxxxxxxxxxxxxxxxxxxxxk.",
		"..kkkkkkkkkkkkkkkkkkkk..",
		"...kNNkhhhhhhhhhhkNNk...",
		"..kNNkhhhhhhhhhhhhkNNk..",
		"..kNNkhehhhhhhhhehkNNk..",
		"..kNNkhhhhhHHhhhhhkNNk..",
		"..kNNkhhhhhHHhhhhhkNNk..",
		"..kNNkhkkkkkkkkkkhkNNk..",
		"..kNNkhhhwhhhhwhhhkNNk..",
		"..kNNNkhhhhhhhhhhkNNNk..",
		"...kNNNkkkhhhhkkkNNNk...",
		"...knnnnkkkkkkkknnnnk...",
		"..knnnnnnnnnnnnnnnnnnk..",
		".knnNnnnnnnnnnnnnnnNnnk.",
		".knNNnnnnnnnnnnnnnnNNnk.",
		".kkkkkkkkkkkkkkkkkkkkkk.",
	],
	"ashen_bishop": [
		"..........kkkk..........",
		".........kRRRRk.........",
		"........kRRRRRRk........",
		"........kRRggRRk........",
		".......kRRRggRRRk.......",
		".......kRggggggRk.......",
		".......kRRRggRRRk.......",
		".......kRRRggRRRk.......",
		".......kggggggggk.......",
		"......kbbbbbbbbbbk......",
		"......kbkobbbbokbk......",
		"......kbbbbbbbbbbk......",
		"......kbbkkkkkkbbk......",
		".......kbbbbbbbbk.......",
		"....kkkkkwwwwwwkkkkk....",
		"...kwwwwwwgwwgwwwwwwk...",
		"..kwwwwwwwgwwgwwwwwwwk..",
		"..kwwwKwwwgwwgwwwKwwwk..",
		"..kwwwwwwwgwwgwwwwwwwk..",
		"..kwwwwwwwgwwgwwwwwwwk..",
		"..kKwwwwwwgwwgwwwwwwKk..",
		"..kKKwwwwwgwwgwwwwwKKk..",
		"..kKKKwwwwggggwwwwKKKk..",
		"..kkkkkkkkkkkkkkkkkkkk..",
	],
	"gem": [
		"...k...",
		"..kwk..",
		".ktwtk.",
		"kttttTk",
		"kttTTTk",
		".kTTTk.",
		"..kTk..",
		"...k...",
	],
	"gem_big": [
		".....k.....",
		"....kwk....",
		"...kiwik...",
		"..kiiwiik..",
		".kiiiwiiik.",
		"kiiiiiiiIIk",
		"kiiiiiiIIIk",
		"kIiiiiIIIIk",
		".kIiiIIIIk.",
		"..kIIIIIk..",
		"...kIIIk...",
		"....kIk....",
		".....k.....",
	],
	"coin": [
		".kkk.",
		"kyygk",
		"kygOk",
		"kgOOk",
		".kkk.",
	],
	"coin_big": [
		"..kkk..",
		".kyyyk.",
		"kyyggOk",
		"kyggOOk",
		"kygOOOk",
		".kgOOk.",
		"..kkk..",
	],
	"skull": [
		".kkkk.",
		"kbbbbk",
		"kbkkbk",
		"kbbbbk",
		".kwwk.",
		"..kk..",
	],
	"grave": [
		"..kkkkk..",
		".kqqqqGk.",
		"kqqqqqqGk",
		"kqqqkqqGk",
		"kqqkkkqGk",
		"kqqqkqqGk",
		"kqqqqqqGk",
		"kqqqqqqGk",
		"kqGqqqGGk",
		"kGGGGGGGk",
		"kkkkkkkkk",
	],
	"grave_cross": [
		"..kkk..",
		"..kqk..",
		"kkkqkkk",
		"kqqqqGk",
		"kkkqkkk",
		"..kqk..",
		"..kqk..",
		"..kqk..",
		"..kGk..",
		".kkGkk.",
		".kGGGk.",
		".kkkkk.",
	],
	"bones": [
		"bb.....bb",
		"bbb...bbb",
		"..bb.bb..",
		"...bbb...",
		"..bb.bb..",
		"bbb...bbb",
		"bb.....bb",
	],
	"skull_pile": [
		"...kkk...",
		"..kbbbk..",
		"..kbkbk..",
		".kkkbkkk.",
		"kbbbkbbbk",
		"kbkbkbkbk",
		".kkk.kkk.",
	],
	"candle": [
		".y.",
		".o.",
		"kwk",
		"kwk",
		"kbk",
		"kbk",
		"kbk",
		"kkk",
	],
	"reeds": [
		"...O...",
		".O.O...",
		".O.On.O",
		".n.nn.O",
		".n.n..n",
		"nn.n.nn",
		".n.nn.n",
		".nnn.n.",
		"..nnnn.",
		"...nn..",
	],
	"stump": [
		"..kkkkkk..",
		".kccCccck.",
		"kcCccccCck",
		"kCccccccck",
		"kCCcccccCk",
		"kkCCCCCCkk",
		"k.kk..kk.k",
	],
	"pew": [
		"kkkkkkkkkkkkkkkkkkkkkkkk",
		"kcccccccccccccccccccccck",
		"kCCCCCCCCCCCCCCCCCCCCCCk",
		"kkkkkkkkkkkkkkkkkkkkkkkk",
		"kcccccccccccccccccccccck",
		"kCCCCCCCCCCCCCCCCCCCCCCk",
		"kkkkkkkkkkkkkkkkkkkkkkkk",
		".kk..................kk.",
	],
	"pillar_stump": [
		"...kkkkkk...",
		".kkqqqqqGkk.",
		"kqqqqqqqqqGk",
		"kGqqqqqqqGGk",
		"kkGGGGGGGGkk",
		".kqqGqqGqqk.",
		".kqqGqqGqqk.",
		".kqqGqqGqqk.",
		".kqqGqqGqGk.",
		"kkGGGGGGGGkk",
		"kGGGGGGGGGGk",
		"kkkkkkkkkkkk",
	],
	"candelabra": [
		"y...y...y",
		"o...o...o",
		"w...w...w",
		"g...g...g",
		"g...g...g",
		"gg..g..gg",
		".ggggggg.",
		"....g....",
		"....g....",
		"...ggg...",
		"..ggggg..",
		"..kkkkk..",
	],
	"rubble": [
		"..kk....",
		".kqGk.kk",
		"kqqGkkGk",
		"kGGkkqGk",
		".kk..kk.",
	],
	"wanderer_walk_1": [
		"....kkkk....",
		"...kPPPPk...",
		"..kPPPPPPk..",
		"..kPkkkkPk..",
		".kPkekkekPk.",
		".kPkkkkkkPk.",
		".kPPkkkkPPk.",
		"kPPPPPPPPPPk",
		"kpPPPPPPPPpk",
		"kpPPPPPPPPpk",
		"kppPPPPPPppk",
		".kppPPPPppk.",
		".kkppppppkk.",
		".kkk....kk..",
	],
	"wanderer_walk_2": [
		"....kkkk....",
		"...kPPPPk...",
		"..kPPPPPPk..",
		"..kPkkkkPk..",
		".kPkekkekPk.",
		".kPkkkkkkPk.",
		".kPPkkkkPPk.",
		"kPPPPPPPPPPk",
		"kpPPPPPPPPpk",
		"kpPPPPPPPPpk",
		"kppPPPPPPppk",
		".kppPPPPppk.",
		".kkppppppkk.",
		"..kk....kkk.",
	],
	"gravekeeper_walk_1": [
		"...kkkkkkkk...",
		"...kxxxxxxk...",
		"...kxxxxxxk...",
		".kkkxxxxxxkkk.",
		"kxxxxxxxxxxxxk",
		".kkkkkkkkkkkk.",
		"..kffffffffk..",
		"..kfekffkefk..",
		"..kffffffffk..",
		".kPkBBBBBBkPk.",
		"kPPPkBBBBkPPPk",
		"kPPPPkkkkPPPPk",
		"kpPPPPPPPPPPpk",
		"kpPPPPPPPPPPpk",
		".kppppppppppk.",
		".kkk......kk..",
	],
	"gravekeeper_walk_2": [
		"...kkkkkkkk...",
		"...kxxxxxxk...",
		"...kxxxxxxk...",
		".kkkxxxxxxkkk.",
		"kxxxxxxxxxxxxk",
		".kkkkkkkkkkkk.",
		"..kffffffffk..",
		"..kfekffkefk..",
		"..kffffffffk..",
		".kPkBBBBBBkPk.",
		"kPPPkBBBBkPPPk",
		"kPPPPkkkkPPPPk",
		"kpPPPPPPPPPPpk",
		"kpPPPPPPPPPPpk",
		".kppppppppppk.",
		"..kk......kkk.",
	],
	"hexblade_witch_walk_1": [
		".....kk.....",
		"....kxxk....",
		"....kxxk....",
		"...kxxxxk...",
		"...kxxxxk...",
		"..kxxxxxxk..",
		"kkkxxxxxxkkk",
		".kkkkkkkkkk.",
		"..kffffffk..",
		"..kfeffefk..",
		"..kffffffk..",
		".kPkkkkkkPk.",
		"kPPPPPPPPPPk",
		"kpPPPPPPPPpk",
		".kpppPPpppk.",
		".kkkkkkkk...",
	],
	"hexblade_witch_walk_2": [
		".....kk.....",
		"....kxxk....",
		"....kxxk....",
		"...kxxxxk...",
		"...kxxxxk...",
		"..kxxxxxxk..",
		"kkkxxxxxxkkk",
		".kkkkkkkkkk.",
		"..kffffffk..",
		"..kfeffefk..",
		"..kffffffk..",
		".kPkkkkkkPk.",
		"kPPPPPPPPPPk",
		"kpPPPPPPPPpk",
		".kpppPPpppk.",
		"...kkkkkkkk.",
	],
	"necromancer_walk_1": [
		"....kkkk....",
		"...kxxxxk...",
		"..kxxxxxxk..",
		"..kxbbbbxk..",
		"..kxrbbrxk..",
		"..kxbbbbxk..",
		"..kxbkkbxk..",
		".kPkxbbxkPk.",
		"kPPPkkkkPPPk",
		"kpPPPPPPPPpk",
		"kpPPPuuPPPpk",
		"kpPPPPPPPPpk",
		".kpPPPPPPpk.",
		".kppPPPPppk.",
		"..kppppppk..",
		"..kkk...kkk.",
	],
	"necromancer_walk_2": [
		"....kkkk....",
		"...kxxxxk...",
		"..kxxxxxxk..",
		"..kxbbbbxk..",
		"..kxrbbrxk..",
		"..kxbbbbxk..",
		"..kxbkkbxk..",
		".kPkxbbxkPk.",
		"kPPPkkkkPPPk",
		"kpPPPPPPPPpk",
		"kpPPPuuPPPpk",
		"kpPPPPPPPPpk",
		".kpPPPPPPpk.",
		".kppPPPPppk.",
		"..kppppppk..",
		".kkk...kkk..",
	],
	"shambler_walk_1": [
		"...kkkkkk...",
		"..kssssssk..",
		".kssssssssk.",
		".ksrssssrsk.",
		".kssssssssk.",
		".kSkkkkkkSk.",
		"..kSSSSSSk..",
		"ksOOOOOOOOsk",
		"kSkOOOOOOkSk",
		".k.OROORO.k.",
		"..kRk..kRk..",
		"..kk....kk..",
	],
	"shambler_walk_2": [
		"...kkkkkk...",
		"..kssssssk..",
		".kssssssssk.",
		".ksrssssrsk.",
		".kssssssssk.",
		".kSkkkkkkSk.",
		"..kSSSSSSk..",
		"ksOOOOOOOOsk",
		"kSkOOOOOOkSk",
		".k.OROORO.k.",
		"...kRkkRk...",
		"....kkkk....",
	],
	"ghoul_walk_1": [
		"......kkkkkkkk......",
		"....kkRRRRRRRRkk....",
		"...kRRRRRRRRRRRRk...",
		"..kRRrrrrrrrrrrRRk..",
		"..kRrrrrrrrrrrrrRk..",
		".kRrrerrrrrrrrerrRk.",
		".kRrrrrrrrrrrrrrrRk.",
		".kRrkwkwkwwkwkwkrRk.",
		".kRrrkkkkkkkkkkrrRk.",
		"kRRrrrrrrrrrrrrrrRRk",
		"kRrrrrrrrrrrrrrrrrRk",
		"krRkrrrrrrrrrrrrkRrk",
		"krRkrrrrrrrrrrrrkRrk",
		"kwwkRrrrrrrrrrrRkwwk",
		".kk.kRrrrrrrrrRk.kk.",
		"....kRRrrrrrrRRk....",
		"....kRRRRRRRRRRk....",
		"....kRRkkkkkkRRk....",
		"...kRRk......kRRk...",
		"...kkkk......kkkk...",
	],
	"ghoul_walk_2": [
		"......kkkkkkkk......",
		"....kkRRRRRRRRkk....",
		"...kRRRRRRRRRRRRk...",
		"..kRRrrrrrrrrrrRRk..",
		"..kRrrrrrrrrrrrrRk..",
		".kRrrerrrrrrrrerrRk.",
		".kRrrrrrrrrrrrrrrRk.",
		".kRrkwkwkwwkwkwkrRk.",
		".kRrrkkkkkkkkkkrrRk.",
		"kRRrrrrrrrrrrrrrrRRk",
		"kRrrrrrrrrrrrrrrrrRk",
		"krRkrrrrrrrrrrrrkRrk",
		"krRkrrrrrrrrrrrrkRrk",
		"kwwkRrrrrrrrrrrRkwwk",
		".kk.kRrrrrrrrrRk.kk.",
		"....kRRrrrrrrRRk....",
		"....kRRRRRRRRRRk....",
		".....kRRkkkkRRk.....",
		".....kRRk..kRRk.....",
		".....kkkk..kkkk.....",
	],
	"cultist_walk_1": [
		"....kkkk....",
		"...kmmmmk...",
		"..kmmmmmmk..",
		"..kmkkkkmk..",
		".kmkekkekmk.",
		".kmkkkkkkmk.",
		".kmmkkkkmmk.",
		"kmmmmmmmmmmk",
		"kMmmgmmgmmMk",
		"kMmmmmmmmmMk",
		"kMMmmmmmmMMk",
		".kMMmmmmMMk.",
		".kMMMMMMMMk.",
		".kkkkkkkk...",
	],
	"cultist_walk_2": [
		"....kkkk....",
		"...kmmmmk...",
		"..kmmmmmmk..",
		"..kmkkkkmk..",
		".kmkekkekmk.",
		".kmkkkkkkmk.",
		".kmmkkkkmmk.",
		"kmmmmmmmmmmk",
		"kMmmgmmgmmMk",
		"kMmmmmmmmmMk",
		"kMMmmmmmmMMk",
		".kMMmmmmMMk.",
		".kMMMMMMMMk.",
		"...kkkkkkkk.",
	],
	"fallen_paladin_walk_1": [
		"......kkkkkk......",
		".....kLllllLk.....",
		"....kLllllllLk....",
		"....kLllllllLk....",
		"....kkooooookk....",
		"....kLllllllLk....",
		"...kkLLLLLLLLkk...",
		".kkllkLllllLkllkk.",
		"kllllkLlgglLkllllk",
		"kLLLLkLlgglLkLLLLk",
		"kLLkkLLlgglLLkkLLk",
		".kk.kLLllllLLk.kk.",
		"....kLLllllLLk....",
		"....kLLLLLLLLk....",
		"....kLLkkkkLLk....",
		"...kLLk....kLLk...",
		"...kLLk....kLLk...",
		"...kkkk....kkkk...",
	],
	"fallen_paladin_walk_2": [
		"......kkkkkk......",
		".....kLllllLk.....",
		"....kLllllllLk....",
		"....kLllllllLk....",
		"....kkooooookk....",
		"....kLllllllLk....",
		"...kkLLLLLLLLkk...",
		".kkllkLllllLkllkk.",
		"kllllkLlgglLkllllk",
		"kLLLLkLlgglLkLLLLk",
		"kLLkkLLlgglLLkkLLk",
		".kk.kLLllllLLk.kk.",
		"....kLLllllLLk....",
		"....kLLLLLLLLk....",
		"....kLLkkkkLLk....",
		".....kLLkkLLk.....",
		".....kLLkkLLk.....",
		".....kkkkkkkk.....",
	],
	"mire_crawler_walk_1": [
		"..k.kk.k..",
		"...kkkk...",
		"..knnnnk..",
		".knennenk.",
		"knnnnnnnnk",
		"kNnNnnNnNk",
		".k.kNNNk.k",
		"k..kkkk..k",
	],
	"mire_crawler_walk_2": [
		"..k.kk.k..",
		"...kkkk...",
		"..knnnnk..",
		".knennenk.",
		"knnnnnnnnk",
		"kNnNnnNnNk",
		"k.kNNNNk.k",
		".k.kkkk.k.",
	],
	"cultist_attack": [
		"....kkkk....",
		"...kmmmmk...",
		"..kmmmmmmk..",
		"..kmkkkkmk..",
		".kmkwkkwkmk.",
		".kmkkkkkkmk.",
		".kmmkkkkmmk.",
		"kmmmmmmmmmmk",
		"kMmmymmymmMk",
		"kMmmmmmmmmMk",
		"kMMmmmmmmMMk",
		".kMMmmmmMMk.",
		".kMMMMMMMMk.",
		"..kkkkkkkk..",
	],
	"plague_spitter_attack": [
		"...kkkkkk...",
		"..kaaaaaak..",
		".kaaaaaaaak.",
		".kaeaaaaeak.",
		"kaaaaaaaaaak",
		"kaAkkkkkkAak",
		"kaAvvvvvvAak",
		"kaAkvvvvkAak",
		"kAaaaaaaaaAk",
		".kAAaaaaAAk.",
		"..kAAAAAAk..",
		"...kkkkkk...",
	],
	"fallen_paladin_attack": [
		"......kkkkkk......",
		".....kLllllLk.....",
		"....kLllllllLk....",
		"....kLllllllLk....",
		"....kkyyyyyykk....",
		"....kLllllllLk....",
		"...kkLLLLLLLLkk...",
		".kkllkLllllLkllkk.",
		"kllllkLlgglLkllllk",
		"kLLLLkLlgglLkLLLLk",
		"kLLkkLLlgglLLkkLLk",
		".kk.kLLllllLLk.kk.",
		"....kLLllllLLk....",
		"....kLLLLLLLLk....",
		"....kLLkkkkLLk....",
		"....kLLk..kLLk....",
		"....kLLk..kLLk....",
		"....kkkk..kkkk....",
	],
	"bone_warden_attack": [
		"k......................k",
		"kk....................kk",
		".kBk................kBk.",
		".kBBk..............kBBk.",
		"..kBBk..kkkkkkkk..kBBk..",
		"...kBBkkbbbbbbbbkkBBk...",
		"....kkbbbbbbbbbbbbkk....",
		"....kbbbbbbbbbbbbbbk....",
		"...kbbbbbbbbbbbbbbbbk...",
		"...kbbkkkkbbbbkkkkbbk...",
		"...kbbkookbbbbkookbbk...",
		"...kbbkkkkbbbbkkkkbbk...",
		"...kbbbbbbbkkbbbbbbbk...",
		"...kBbbbbbbbbbbbbbbBk...",
		"....kBbbbbbbbbbbbbBk....",
		"....kBkwkwkwwkwkwkBk....",
		"....kBRRRRRRRRRRRRBk....",
		".....kBbbbbbbbbbbBk.....",
		"......kkBBBBBBBBkk......",
		"........kkkkkkkk........",
		"...kk.kKKKKKKKKKKk.kk...",
		"..kKKkKKKKKKKKKKKKkKKk..",
		".kKKKKKKKKKKKKKKKKKKKKk.",
		".kkkkkkkkkkkkkkkkkkkkkk.",
	],
	"mire_hag_attack": [
		"...........kk...........",
		"..........kxxk..........",
		".........kxxxxk.........",
		".........kxxxxk.........",
		"........kxxxxxxk........",
		"........kxxxxxxk........",
		".......kxxxxxxxxk.......",
		"..kkkkkkxxxxxxxxkkkkkk..",
		".kxxxxxxxxxxxxxxxxxxxxk.",
		"..kkkkkkkkkkkkkkkkkkkk..",
		"...kNNkhhhhhhhhhhkNNk...",
		"..kNNkhhhhhhhhhhhhkNNk..",
		"..kNNkhvhhhhhhhhvhkNNk..",
		"..kNNkhhhhhHHhhhhhkNNk..",
		"..kNNkhhhhhHHhhhhhkNNk..",
		"..kNNkhRRRRRRRRRRhkNNk..",
		"..kNNkhhhwhhhhwhhhkNNk..",
		"..kNNNkhhhhhhhhhhkNNNk..",
		"...kNNNkkkhhhhkkkNNNk...",
		"...knnnnkkkkkkkknnnnk...",
		"..knnnnnnnnnnnnnnnnnnk..",
		".knnNnnnnnnnnnnnnnnNnnk.",
		".knNNnnnnnnnnnnnnnnNNnk.",
		".kkkkkkkkkkkkkkkkkkkkkk.",
	],
	"ashen_bishop_attack": [
		"..........kkkk..........",
		".........kRRRRk.........",
		"........kRRRRRRk........",
		"........kRRyyRRk........",
		".......kRRRyyRRRk.......",
		".......kRyyyyyyRk.......",
		".......kRRRyyRRRk.......",
		".......kRRRyyRRRk.......",
		".......kyyyyyyyyk.......",
		"......kbbbbbbbbbbk......",
		"......kbkybbbbykbk......",
		"......kbbbbbbbbbbk......",
		"......kbbkkkkkkbbk......",
		".......kbbbbbbbbk.......",
		"....kkkkkwwwwwwkkkkk....",
		"...kwwwwwwywwywwwwwwk...",
		"..kwwwwwwwywwywwwwwwwk..",
		"..kwwwKwwwywwywwwKwwwk..",
		"..kwwwwwwwywwywwwwwwwk..",
		"..kwwwwwwwywwywwwwwwwk..",
		"..kKwwwwwwywwywwwwwwKk..",
		"..kKKwwwwwywwywwwwwKKk..",
		"..kKKKwwwwyyyywwwwKKKk..",
		"..kkkkkkkkkkkkkkkkkkkk..",
	],
	"coin_1": [
		"..k..",
		".kgk.",
		".kyk.",
		".kOk.",
		"..k..",
	],
	"coin_big_1": [
		"...k...",
		"..kyk..",
		"..kgk..",
		"..kgk..",
		"..kOk..",
		"..kOk..",
		"...k...",
	],
	"gem_mid": [
		"....k....",
		"...kwk...",
		"..kvwvk..",
		".kvvwvvk.",
		"kvvvvvVVk",
		"kvvvvVVVk",
		"kVvvVVVVk",
		".kVVVVVk.",
		"..kVVVk..",
		"...kVk...",
		"....k....",
	],
	# Auto weapon icons (HUD, run summary, altars). Named in each weapon's .tres.
	"icon_orbiting_skulls": [
		"..kkkkk..",
		".kbbbbbk.",
		"kbbbbbbbk",
		"kbkkbkkbk",
		"kbkkbkkbk",
		"kbbbkbbbk",
		".kbbbbbk.",
		"..kbwbk..",
		"...kkk...",
	],
	"icon_seeking_bolts": [
		"....kkkk.",
		"...kttwwk",
		"....kttwk",
		"....ktttk",
		"...ktTktk",
		"..ktTk.k.",
		".ktTk....",
		"ktTk.....",
		"kTk......",
	],
	"icon_holy_aura": [
		"..kkkkk..",
		".keyyyek.",
		"keykkkyek",
		"kyk...kyk",
		"kyk...kyk",
		"kyk...kyk",
		"keykkkyek",
		".keyyyek.",
		"..kkkkk..",
	],
	# Level-up upgrades (up_), shop relics (rel_), weapon breakdown and run summary icons.
	"up_sharpened_bolts": [
		"......kkk",
		".....kwwk",
		"....kwlk.",
		"...kwlk..",
		"k.kwlk...",
		"kgklk....",
		".kgk.....",
		"kckgk....",
		"kk.kk....",
	],
	"up_quick_hands": [
		"....kkkk.",
		"...keeek.",
		"..keeek..",
		".keeekkk.",
		"keeeeeek.",
		"kkkkeek..",
		"...keek..",
		"..keek...",
		"..kkk....",
	],
	"up_fleet_foot": [
		".kkkkkk..",
		"w.kCCk...",
		"wwkcck...",
		"wwkcck...",
		".wkcckkk.",
		"..kccccck",
		"..kccccck",
		"..kkk.kkk",
		".........",
	],
	"up_heart_container": [
		".kk...kk.",
		"krrk.krrk",
		"krwrkrrrk",
		"krrrrrrrk",
		"kRrrrrrRk",
		".kRrrrRk.",
		"..kRrRk..",
		"...kRk...",
		"....k....",
	],
	"up_extra_bolt": [
		"...kkk...",
		"..kwttk..",
		"..ktttk..",
		"...kTk...",
		"kkk.k.kkk",
		"kttk.kttk",
		"kTtk.kTtk",
		".kk...kk.",
		".........",
	],
	"up_piercing_bolts": [
		"....k....",
		"...kwk...",
		"..kwtwk..",
		"kkkktkkkk",
		"kBBBtBBBk",
		"kkkktkkkk",
		"...ktk...",
		"...kTk...",
		"....k....",
	],
	"up_grave_magnet": [
		".kkk.kkk.",
		"krrk.klk.",
		"krk...kl.",
		"krk...klk",
		"krk...klk",
		".krkkklk.",
		"..krrrk..",
		"...kkk...",
		".........",
	],
	"up_shadow_step": [
		"..kkkkk..",
		".kUUeUUk.",
		"kUUUeUUUk",
		"kUUUeUUUk",
		"kUUUeeeUk",
		"kUUUUUUUk",
		"kUUUUUUUk",
		".kUUUUUk.",
		"..kkkkk..",
	],
	"up_blood_draught": [
		"...kkk...",
		"...kwk...",
		"..kkwkk..",
		".kwrrrwk.",
		"krrrrrrrk",
		"krrrrrrrk",
		"kRrrrrrRk",
		".kRRRRRk.",
		"..kkkkk..",
	],
	"up_long_shot": [
		".........",
		"......k..",
		"......kk.",
		"kkkkkkkwk",
		"LLLLlwwwk",
		"kkkkkkkwk",
		"......kk.",
		"......k..",
		".........",
	],
	"up_steady_nerves": [
		".kkkkkkk.",
		"klllwlllk",
		"klllwlllk",
		"klwwwwwlk",
		"klllwlllk",
		".kLlwlLk.",
		"..kLlLk..",
		"...kLk...",
		"....k....",
	],
	"up_swift_bolts": [
		".........",
		".....kkk.",
		"tt..kwwtk",
		"...kwttTk",
		"ttTkttTk.",
		"...kTTk..",
		"tt.kkk...",
		".........",
		".........",
	],
	"up_arcane_focus": [
		"...kkk...",
		".kkiiikk.",
		"kIiiwiiIk",
		"kIiwwwiIk",
		"kIiiwiiIk",
		"kIIiiiIIk",
		".kkIIIkk.",
		"..kbbbk..",
		".kkkkkkk.",
	],
	"up_keen_edge": [
		"....k....",
		"...kek...",
		"kkkkekkkk",
		"keeeweeek",
		".kewwwek.",
		"..keeek..",
		".kekkkek.",
		".kk...kk.",
		".........",
	],
	"up_corpse_blast": [
		"v..v.v..v",
		".vkkkkkv.",
		"vkbbbbbkv",
		".kbkbkbk.",
		".kbbbbbk.",
		"v.kbkbk.v",
		"..kkkkk..",
		".v.....v.",
		"v...v...v",
	],
	"up_giant_slayer": [
		"e...e...e",
		"k...k...k",
		"kk.kek.kk",
		"kekeeekek",
		"keeeeeeek",
		"kereeerek",
		"keeeeeeek",
		"kkkkkkkkk",
		".........",
	],
	"up_executioner": [
		".kkk.....",
		"kwllk....",
		"klllkk...",
		"kLlkcck..",
		".kkkcck..",
		"....kcck.",
		".....kcck",
		"......kck",
		".......k.",
	],
	"up_ricochet": [
		"tk.......",
		"ktk......",
		".ktk...kk",
		"..ktk.kwk",
		"...ktkwk.",
		"....kwk..",
		".....k...",
		"kkkkkkkkk",
		"LLLLLLLLL",
	],
	"up_hunting_bolts": [
		".....kkk.",
		"....krwrk",
		"....kwrwk",
		"....krwrk",
		"..tt.kkk.",
		".t.......",
		".t.......",
		"t........",
		"T........",
	],
	"up_glass_cannon": [
		".kk...kk.",
		"krrk.krrk",
		"krwrkkrrk",
		"krrrkrrrk",
		"kRrrrkrRk",
		".kRrkrRk.",
		"..kRkRk..",
		"...kRk...",
		"....k....",
	],
	"up_reckless_haste": [
		"....k....",
		"...kok...",
		"..koook..",
		".kooeook.",
		".koeeeok.",
		"kooeyeook",
		"kOoeyeoOk",
		".kOoooOk.",
		"..kkkkk..",
	],
	"up_afterimage": [
		".........",
		".........",
		"L..l..w..",
		".L..l..w.",
		"..L..l..w",
		".L..l..w.",
		"L..l..w..",
		".........",
		".........",
	],
	"up_hallowed_blast": [
		"....e....",
		".e.kkk.e.",
		"..kiwik..",
		".kiwewik.",
		"ekweeewke",
		".kiwewik.",
		"..kiwik..",
		".e.kkk.e.",
		"....e....",
	],
	"up_deep_hex": [
		".........",
		"..kkkkk..",
		".kuuuuuk.",
		"kuummmuuk",
		"kummkmmuk",
		"kuummmuuk",
		".kuuuuuk.",
		"..kkkkk..",
		".........",
	],
	"up_ossuary": [
		"kk.....kk",
		"kbk...kbk",
		".kbk.kbk.",
		"..kbkbk..",
		"...kbk...",
		"..kbkbk..",
		".kbk.kbk.",
		"kbk...kbk",
		"kk.....kk",
	],
	"up_twin_scythes": [
		"kkk..kkk.",
		"wlck.wlck",
		"k.ck.k.ck",
		"..ck...ck",
		".ck...ck.",
		".ck...ck.",
		"ck...ck..",
		"ck...ck..",
		"k....k...",
	],
	"up_long_reach": [
		"..kkk....",
		".kwwlk...",
		"k...lk...",
		"....lk...",
		"...lk..w.",
		"..lk.wwww",
		".lk....w.",
		"lk.......",
		"k........",
	],
	"up_heavy_blade": [
		".kkkkkkk.",
		"kwwwwwllk",
		"kllkkkkck",
		"kk....kck",
		".....kck.",
		"....kck..",
		"...kck...",
		"..kck....",
		"..kk.....",
	],
	"up_grim_harvest": [
		"..kkkkk..",
		".kwwwlck.",
		"kwlkkkck.",
		"klk..kck.",
		".k..kck..",
		"r..kck...",
		"R.kck..r.",
		".kck...R.",
		".kk......",
	],
	"up_forked_lightning": [
		"...ww....",
		"....tw...",
		"...tw....",
		"..twt....",
		".tw..t...",
		"tw....tw.",
		"w......tw",
		".........",
		".........",
	],
	"up_long_arc": [
		"......ww.",
		".....tw..",
		"....tw...",
		"...twwww.",
		"....wt...",
		"...wt....",
		"..wt.....",
		".........",
		"kkkkkkkkk",
	],
	"up_conductor": [
		".......t.",
		"......tw.",
		".......t.",
		"......kkk",
		"...kkkkwk",
		"...kwkkwk",
		"kkkkwkkwk",
		"kwkkwkkwk",
		"kkkkkkkkk",
	],
	"up_split_bolt": [
		"tw.....tw",
		".tw...tw.",
		"..tw.tw..",
		"...twt...",
		"....w....",
		"...tw....",
		"..tw.....",
		".tw......",
		"tw.......",
	],
	"up_longer_row": [
		".........",
		"w..w..w..",
		"b..b..b.w",
		"b..b..b.b",
		"B..B..B.b",
		"B..B..B.B",
		"kkkkkkkkk",
		"KKKKKKKKK",
		".........",
	],
	"up_wide_spikes": [
		"....w....",
		"...wbw...",
		"...bbb...",
		"..bbBbb..",
		"..bBBBb..",
		".bBB.BBb.",
		".BB...BB.",
		"kkkkkkkkk",
		"KKKKKKKKK",
	],
	"up_quick_rise": [
		"w...w....",
		"b..www...",
		"b.w.w.w..",
		"b...w....",
		"B...w....",
		"B........",
		"kkkkkkkkk",
		"KKKKKKKKK",
		".........",
	],
	"up_splinters": [
		"w...w...w",
		".w..b..w.",
		"..w.b.w..",
		"....b....",
		"w...B...w",
		"....B....",
		"kkkkkkkkk",
		"KKKKKKKKK",
		".........",
	],
	"rel_cursed_skull": [
		"..kkkkk..",
		".kbbbbbk.",
		"kbbbbbbbk",
		"kbkrbkrbk",
		"kbkkbkkbk",
		"kbbbkbbbk",
		".kbbbbbk.",
		"..kbkbk..",
		"...kkk...",
	],
	"rel_iron_boots": [
		".kkkkkk..",
		".kLLLLk..",
		"..kllk...",
		"..klwk...",
		"..kllkkk.",
		"..klllllk",
		"..kLLLLLk",
		"..kkk.kkk",
		".........",
	],
	"rel_hourglass": [
		"kkkkkkkkk",
		".kwwwwwk.",
		"..keeek..",
		"...kek...",
		"....k....",
		"...kwk...",
		"..kweek..",
		".keeeeek.",
		"kkkkkkkkk",
	],
	"rel_grave_lantern": [
		"...kkk...",
		"..k...k..",
		".kkkkkkk.",
		".kgeyegk.",
		".keyyyek.",
		".kgeyegk.",
		".kkkkkkk.",
		"..kgggk..",
		"...kkk...",
	],
	"rel_bone_charm": [
		".kk...kk.",
		"kbbk.kbbk",
		"kbbbkbbbk",
		".kbbbbbk.",
		"..kbbbk..",
		".kbbbbbk.",
		"kbbbkbbbk",
		"kbbk.kbbk",
		".kk...kk.",
	],
	"rel_hunters_eye": [
		".........",
		"..kkkkk..",
		".kwwwwwk.",
		"kwwkkkwwk",
		"kwkaAakwk",
		"kwwkkkwwk",
		".kwwwwwk.",
		"..kkkkk..",
		".........",
	],
	"rel_vampire_fang": [
		".kkkkkkk.",
		"kRrrrrrRk",
		"kwkkkkkwk",
		"kwk...kwk",
		"kwk...kwk",
		".kwk.kwk.",
		"..k...k..",
		"......r..",
		"......r..",
	],
	"rel_holy_water": [
		"...kkk...",
		"...kbk...",
		"..kkbkk..",
		".ktttttk.",
		"ktttwtttk",
		"kttwwwttk",
		"ktttwtttk",
		".kTTTTTk.",
		"..kkkkk..",
	],
	"rel_mourners_bell": [
		"....k....",
		"...kgk...",
		"..keegk..",
		"..keegk..",
		".keeeegk.",
		".keeeegk.",
		"kgggggggk",
		"kkkkgkkkk",
		"....k....",
	],
	"icon_main_gun": [
		".........",
		".....k...",
		".....kk..",
		"kkkkkkwk.",
		"kbbbbwwwk",
		"kkkkkkwk.",
		".....kk..",
		".....k...",
		".........",
	],
	"icon_ability": [
		"....k....",
		"...kik...",
		"k.kiwik.k",
		"kikiwikik",
		".kiwwwik.",
		"kikiwikik",
		"k.kiwik.k",
		"...kik...",
		"....k....",
	],
	"star": [
		"...k...",
		"..kek..",
		"kkkekkk",
		"keeyeek",
		".keyek.",
		".kekek.",
		"kk...kk",
	],
	# Power-up pickups (pickup_), the newer auto weapons and their effects.
	"pickup_heart": [
		".kk...kk.",
		"krrk.krrk",
		"krwrrrrRk",
		"krrrrrrRk",
		".krrrrRk.",
		"..krrRk..",
		"...kRk...",
		"....k....",
	],
	"pickup_magnet": [
		"..kkkkk..",
		".kttttTk.",
		"kttkkkTTk",
		"ktk...kTk",
		"ktk...kTk",
		"ktk...kTk",
		"kwk...kwk",
		"kwk...kwk",
		"kkk...kkk",
	],
	"pickup_bomb": [
		"......y..",
		".....kc..",
		"..kkkck..",
		".kKKeKKk.",
		"kKKeeeKKk",
		"kKKKeKKKk",
		"kKKKeKKxk",
		".kKKKKxk.",
		"..kkkkk..",
	],
	"pickup_frost": [
		"kkkkkkk",
		".ktttk.",
		".kwtTk.",
		"..kTk..",
		"...k...",
		"..ktk..",
		".kwttk.",
		".ktTTk.",
		"kkkkkkk",
	],
	"icon_chain_lightning": [
		".....kkk.",
		"....kwtk.",
		"...kwtk..",
		"..kwtkkk.",
		".kwwwwtk.",
		".kkktTk..",
		"...ktTk..",
		"..ktTk...",
		"..kkk....",
	],
	"icon_reapers_scythe": [
		"..kkkkk..",
		".kwwwlck.",
		"kwlkkkck.",
		"klk..kck.",
		".k..kck..",
		"...kck...",
		"..kck....",
		".kck.....",
		".kk......",
	],
	"scythe": [
		"..kkkkk..",
		".kwwwlck.",
		"kwlkkkck.",
		"klk..kck.",
		".k..kck..",
		"...kck...",
		"..kck....",
		".kck.....",
		".kk......",
	],
	"icon_hellfire_trail": [
		"....k....",
		"...kok...",
		"..koyok..",
		".koyyyok.",
		".koyeyok.",
		"koyeweyok",
		"koyeeeyok",
		".kOoooOk.",
		"..kkkkk..",
	],
	"flame": [
		"..o..",
		".oyo.",
		".oyo.",
		"oyeyo",
		"oyeyo",
		".OoO.",
	],
	"flame_1": [
		"...o.",
		"..oo.",
		".oyo.",
		"oyeyo",
		"oyeyo",
		".OoO.",
	],
	"icon_bone_spears": [
		"....k....",
		"...kwk...",
		"..kwbBk..",
		"...kbk...",
		"...kbk...",
		"...kBk...",
		"..kkBkk..",
		".kBBBBBk.",
		"kkkkkkkkk",
	],
	"bone_spear": [
		"..k..",
		".kwk.",
		"kwbBk",
		".kbk.",
		".kbk.",
		".kbk.",
		".kbk.",
		".kBk.",
		".kBk.",
		".kbk.",
		".kBk.",
		"kkBkk",
		"kBBBk",
	],
	# Map events: champion chests, the champion's crown, the ritual, the thief.
	"chest": [
		".kkkkkkkkk.",
		"kccccccccck",
		"kcCCCCCCCck",
		"kkkkkekkkkk",
		"kcccgegccck",
		"kcccckcccck",
		"kCcccccccCk",
		"kCCCCCCCCCk",
		".kkkkkkkkk.",
	],
	# Minimap markers: tiny shapes in "P" (tinted with the marker's color); the
	# minimap draws a dark outline around them.
	"mm_champion": [
		"P.P.P",
		"PPPPP",
		"PPPPP",
	],
	"mm_ritual": [
		".PPP.",
		"P...P",
		"P...P",
		"P...P",
		".PPP.",
	],
	"mm_coin": [
		".PPP.",
		"PPPPP",
		"PP.PP",
		"PPPPP",
		".PPP.",
	],
	"mm_chest": [
		"PPPPP",
		"P.P.P",
		"PPPPP",
		"PPPPP",
	],
	"mm_altar": [
		"..P..",
		"..P..",
		"..P..",
		".PPP.",
		"..P..",
	],
	"mm_boss": [
		".PPPPP.",
		"PPPPPPP",
		"P..P..P",
		"PPPPPPP",
		".PP.PP.",
		".P.P.P.",
	],
	"mm_you": [
		"..P..",
		".PPP.",
		"PPwPP",
		".PPP.",
		"..P..",
	],
	"mm_teammate": [
		".P.",
		"PPP",
		".P.",
	],
	"mm_downed": [
		"..P..",
		"..P..",
		"PPPPP",
		"..P..",
		"..P..",
	],
	"crown": [
		"e..e..e",
		"ee.e.ee",
		"eeeeeee",
		"eyryrye",
		"ggggggg",
	],
	"icon_ritual": [
		"..kkkkk..",
		".kiiiiik.",
		"kiIkikIik",
		"kikiiikik",
		"kiiieiiik",
		"kikiiikik",
		"kiIkikIik",
		".kiiiiik.",
		"..kkkkk..",
	],
	"grave_robber": [
		"...kkk...",
		"..kGGGk..",
		".kGGGGGk.",
		".kGeGeGk.",
		"..kGGGk..",
		".kccgcck.",
		"kcckgkcck",
		"kcCcccCck",
		".kcCkCck.",
		".kck.kck.",
		".kk...kk.",
	],
	"grave_robber_walk_1": [
		"...kkk...",
		"..kGGGk..",
		".kGGGGGk.",
		".kGeGeGk.",
		"..kGGGk..",
		".kccgcck.",
		"kcckgkcck",
		"kcCcccCck",
		".kcCkCck.",
		"..kck.kk.",
		"..kk.....",
	],
	"grave_robber_walk_2": [
		"...kkk...",
		"..kGGGk..",
		".kGGGGGk.",
		".kGeGeGk.",
		"..kGGGk..",
		".kccgcck.",
		"kcckgkcck",
		"kcCcccCck",
		".kcCkCck.",
		".kk.kck..",
		".....kk..",
	],
	"icon_quest": [
		".kkkkkkk.",
		"kbbbbbbBk",
		".kbkkkbk.",
		".kbbbbbk.",
		".kbkkbbk.",
		".kbbbbbk.",
		".kbkkkbk.",
		"kbbbbbbBk",
		".kkkkkkk.",
	],
}

const TINT_CHAR: String = "P"
const TINT_SHADE_CHAR: String = "p"

static var _cache: Dictionary[String, ImageTexture] = {}
static var _disc_cache: Dictionary[String, ImageTexture] = {}


static func has_sprite(sprite: String) -> bool:
	return SPRITES.has(sprite)


## "<sprite>_walk_1" / "_walk_2" while moving, else the sprite itself.
## `phase` is any steadily increasing number (e.g. walking time).
static func walk_frame(sprite: String, moving: bool, phase: float) -> String:
	if not moving or not SPRITES.has(sprite + "_walk_1"):
		return sprite
	return sprite + ("_walk_1" if int(phase) % 2 == 0 else "_walk_2")


static func size_of(sprite: String) -> Vector2i:
	var rows: Array = SPRITES[sprite]
	return Vector2i(String(rows[0]).length(), rows.size())


## The sprite as a texture. `tint` recolors the P/p pixels; `flash` makes every
## visible pixel white (hit flash).
static func texture(sprite: String, tint: Color = Color.WHITE, flash: bool = false) -> ImageTexture:
	var key := "%s|%s|%s" % [sprite, tint.to_html(), flash]
	if _cache.has(key):
		return _cache[key]
	var rows: Array = SPRITES[sprite]
	var image := Image.create(String(rows[0]).length(), rows.size(), false, Image.FORMAT_RGBA8)
	var shade := tint.darkened(0.35)
	for y: int in rows.size():
		var row: String = rows[y]
		for x: int in row.length():
			var ch := row[x]
			var color: Color
			if ch == TINT_CHAR:
				color = tint
			elif ch == TINT_SHADE_CHAR:
				color = shade
			else:
				color = PALETTE.get(ch, Color(0, 0, 0, 0))
			if flash and color.a > 0.0:
				color = Color.WHITE
			image.set_pixel(x, y, color)
	var built := ImageTexture.create_from_image(image)
	_cache[key] = built
	return built


## A filled circle (with an optional inner circle on top) baked into a small
## texture: pixels whose centers are within the radius, like draw_circle. Many
## copies of one texture draw in a single batch, far cheaper than draw_circle
## (which builds a polygon and its own draw call every time). Cached.
static func disc_texture(radius: float, color: Color, inner_radius: float = 0.0, inner_color: Color = Color.WHITE) -> ImageTexture:
	var key := "%s|%s|%s|%s" % [radius, color.to_html(), inner_radius, inner_color.to_html()]
	if _disc_cache.has(key):
		return _disc_cache[key]
	var side := ceili(radius) * 2 + 1
	var image := Image.create(side, side, false, Image.FORMAT_RGBA8)
	var middle := side / 2.0
	for y: int in side:
		for x: int in side:
			var distance := Vector2(x + 0.5 - middle, y + 0.5 - middle).length()
			if distance <= inner_radius:
				image.set_pixel(x, y, inner_color)
			elif distance <= radius:
				image.set_pixel(x, y, color)
	var built := ImageTexture.create_from_image(image)
	_disc_cache[key] = built
	return built


## The part of the world this canvas item's viewport shows right now (for
## skipping off-screen drawing), grown by `margin`.
static func visible_rect(canvas: CanvasItem, margin: float = 16.0) -> Rect2:
	var viewport := canvas.get_viewport()
	if viewport == null:
		return Rect2(-1e6, -1e6, 2e6, 2e6)
	var to_world := (canvas.get_global_transform_with_canvas().affine_inverse())
	return (to_world * viewport.get_visible_rect()).grow(margin)


## Draws a sprite centered on `center` from a CanvasItem's _draw().
static func draw(canvas: CanvasItem, sprite: String, center: Vector2, tint: Color = Color.WHITE,
		flash: bool = false, flip: bool = false, scale: float = 1.0, modulate: Color = Color.WHITE) -> void:
	var tex := texture(sprite, tint, flash)
	var size := Vector2(tex.get_size()) * scale
	draw_rect_flipped(canvas, tex, Rect2((center - size / 2.0).round(), size), flip, modulate)


## Draws `tex` filling `rect`, mirrored left/right around the rect's center when
## `flip` is set. (A negative rect width does NOT mirror in Godot: it just
## shifts the image, so we mirror with a temporary transform instead.)
static func draw_rect_flipped(canvas: CanvasItem, tex: Texture2D, rect: Rect2, flip: bool, modulate: Color = Color.WHITE) -> void:
	if not flip:
		canvas.draw_texture_rect(tex, rect, false, modulate)
		return
	var mirror_x := rect.position.x * 2.0 + rect.size.x
	canvas.draw_set_transform(Vector2(mirror_x, 0.0), 0.0, Vector2(-1.0, 1.0))
	canvas.draw_texture_rect(tex, rect, false, modulate)
	canvas.draw_set_transform(Vector2.ZERO, 0.0, Vector2.ONE)
